trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
    - job: BuildJob
      steps:
        - script: echo"Building Application"
          displayName: Build Step
- stage: Deploy
  jobs:
    - job: DeployJob
      steps:
        - script: echo"Deploying Application"
          displayName: Deploy Setp




